### ISSUE TITLE
grib2json is not a function.

### ISSUE THREAD

**Issue by SamalaSumanth0262** [f24-it-services/grib2json#1]
![Screenshot 2020-01-12 at 4 35 29 PM](https://user-images.githubusercontent.com/40859181/72217834-8e100f00-3559-11ea-9dd4-aed1c452df82.png)
I m trying basic example mentioned in the doc and the code as follows
```
 var grib2json = require('grib2json')
console.log("TCL: grib2json", grib2json)
grib2json('gfs.t00z.pgrb2.1p00.f000', {/* options */ }, function (err, json) {
    if (err) return console.error(err)

    console.log(json)
}) 
```
![Screenshot 2020-01-12 at 4 37 27 PM](https://user-images.githubusercontent.com/40859181/72217852-d29baa80-3559-11ea-85e6-1ac2a9839f1a.png)

@extronics  @spurreiter  Can you help me out ?

Thanks in advance.

**Comment by spurreiter** [comment]
@SamalaSumanth0262 Please revise your import. Try using something like 
```js
const grib2json = require('grib2json').default
```

**Comment by SamalaSumanth0262** [comment]
```
const grib2json = require('grib2json').default
grib2json('gfs.t00z.pgrb2.1p00.f000', {/* options */ }, function (err, json) {
    if (err) return console.log("TCL: err", err)
    console.log(json)
})
```
![Screenshot 2020-01-13 at 10 35 19 AM](https://user-images.githubusercontent.com/40859181/72233967-6750e780-35f0-11ea-9263-bf3712428300.png)
I have installed the package from https://www.npmjs.com/package/grib2json?activeTab=readme
and is this package is being maintained ?
@spurreiter 
Thanks in Advance.
